version: '2'

services:

  angular:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: ng

      volumes:
        - .:/src/app
        - /node_modules

      ports:
        - "4200:4200"
